// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	model "Price-Service/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MQ is an autogenerated mock type for the MQ type
type MQ struct {
	mock.Mock
}

// GetPrices provides a mock function with given fields: ctx
func (_m *MQ) GetPrices(ctx context.Context) ([]*model.Price, error) {
	ret := _m.Called(ctx)

	var r0 []*model.Price
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Price); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Price)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMQ interface {
	mock.TestingT
	Cleanup(func())
}

// NewMQ creates a new instance of MQ. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMQ(t mockConstructorTestingTNewMQ) *MQ {
	mock := &MQ{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
